// Snap! — a few facts per element for the hover card (step 2).
// en = Pauling electronegativity (null where none is defined), melt = melting point in °C
// (est:true where it is an estimate), note = one plain sentence (the lit elements first).
window.SNAP_FACTS = {
  H:  { en:2.20, melt:-259, note:'Three quarters of all the ordinary matter in the universe is hydrogen.' },
  He: { en:null, melt:-272, note:'Helium never freezes at ordinary pressure, no matter how cold it gets.' },
  Li: { en:0.98, melt:181,  note:'Lithium is the lightest metal; a lump of it floats on oil.' },
  Be: { en:1.57, melt:1287, note:'Beryllium is transparent to X-rays, so it makes the windows on X-ray tubes.' },
  B:  { en:2.04, melt:2076, note:'Boron makes borosilicate glass, the kind that shrugs off a hot oven.' },
  C:  { en:2.55, melt:3550, note:'Carbon bonds to itself without limit; every living thing is built on those chains.' },
  N:  { en:3.04, melt:-210, note:'Four fifths of every breath is nitrogen, and almost none of it reacts with you.' },
  O:  { en:3.44, melt:-219, note:'Nearly half the mass of the Earth’s crust is oxygen, locked into rock.' },
  F:  { en:3.98, melt:-220, note:'Fluorine pulls harder on electrons than any other element; it even burns glass.' },
  Ne: { en:null, melt:-249, note:'A neon sign glows red-orange because that is the color neon’s electrons give off.' },
  Na: { en:0.93, melt:98,   note:'Sodium is soft enough to cut with a butter knife, and it catches fire in water.' },
  Mg: { en:1.31, melt:650,  note:'Magnesium sits at the center of every chlorophyll molecule, catching sunlight.' },
  Al: { en:1.61, melt:660,  note:'Aluminium was once dearer than gold; Napoleon III served his best guests on it.' },
  Si: { en:1.90, melt:1414, note:'Silicon is the second most common element in the crust, and the heart of every chip.' },
  P:  { en:2.19, melt:44,   note:'White phosphorus glows in the dark as it slowly burns in air.' },
  S:  { en:2.58, melt:115,  note:'Sulfur was the brimstone of the old texts; it burns with a blue flame.' },
  Cl: { en:3.16, melt:-102, note:'A little chlorine keeps a swimming pool clean; a lot of it was a weapon in 1915.' },
  Ar: { en:null, melt:-189, note:'Argon is about one percent of the air, and it is in every light bulb, doing nothing.' },
  K:  { en:0.82, melt:63,   note:'Potassium in bananas is very slightly radioactive; so are you.' },
  Ca: { en:1.00, melt:842,  note:'Calcium is the metal in your bones, chalk, marble and seashells.' },
  Sc: { en:1.36, melt:1541 }, Ti: { en:1.54, melt:1668, note:'Titanium is as strong as steel at half the weight, and the body accepts it as its own.' },
  V:  { en:1.63, melt:1910 }, Cr: { en:1.66, melt:1907, note:'Chromium gives rubies their red and emeralds their green.' },
  Mn: { en:1.55, melt:1246 }, Fe: { en:1.83, melt:1538, note:'Iron is the last element a star can make by fusion; beyond it, fusion costs energy.' },
  Co: { en:1.88, melt:1495 }, Ni: { en:1.91, melt:1455 },
  Cu: { en:1.90, melt:1085, note:'Copper and gold are the only metals with a color of their own.' },
  Zn: { en:1.65, melt:420 }, Ga: { en:1.81, melt:30, note:'Gallium melts in your hand.' },
  Ge: { en:2.01, melt:938 }, As: { en:2.18, melt:817 }, Se: { en:2.55, melt:221 },
  Br: { en:2.96, melt:-7, note:'Bromine is one of only two elements that are liquid at room temperature.' },
  Kr: { en:3.00, melt:-157 }, Rb: { en:0.82, melt:39 }, Sr: { en:0.95, melt:777, note:'Strontium is the red in fireworks.' },
  Y:  { en:1.22, melt:1526 }, Zr: { en:1.33, melt:1855 }, Nb: { en:1.60, melt:2477 }, Mo: { en:2.16, melt:2623 },
  Tc: { en:1.90, melt:2157, note:'Technetium was the first element made by people rather than found.' },
  Ru: { en:2.20, melt:2334 }, Rh: { en:2.28, melt:1964 }, Pd: { en:2.20, melt:1555 },
  Ag: { en:1.93, melt:962, note:'Silver conducts heat and electricity better than any other metal.' },
  Cd: { en:1.69, melt:321 }, In: { en:1.78, melt:157 }, Sn: { en:1.96, melt:232, note:'Tin cries: bend a bar of it and it creaks as the crystals shear.' },
  Sb: { en:2.05, melt:631 }, Te: { en:2.10, melt:450 },
  I:  { en:2.66, melt:114, note:'Iodine goes straight from solid to violet vapor when warmed.' },
  Xe: { en:2.60, melt:-112 }, Cs: { en:0.79, melt:28, note:'A caesium clock defines the second.' },
  Ba: { en:0.89, melt:727 },
  La: { en:1.10, melt:920 }, Ce: { en:1.12, melt:795 }, Pr: { en:1.13, melt:935 }, Nd: { en:1.14, melt:1024, note:'Neodymium makes the strongest permanent magnets there are.' },
  Pm: { en:1.13, melt:1042 }, Sm: { en:1.17, melt:1072 }, Eu: { en:1.20, melt:826 }, Gd: { en:1.20, melt:1312 },
  Tb: { en:1.10, melt:1356 }, Dy: { en:1.22, melt:1407 }, Ho: { en:1.23, melt:1461 }, Er: { en:1.24, melt:1529 },
  Tm: { en:1.25, melt:1545 }, Yb: { en:1.10, melt:824 }, Lu: { en:1.27, melt:1652 },
  Hf: { en:1.30, melt:2233 }, Ta: { en:1.50, melt:3017 }, W: { en:2.36, melt:3422, note:'Tungsten has the highest melting point of any metal; that is why it is the filament.' },
  Re: { en:1.90, melt:3186 }, Os: { en:2.20, melt:3033, note:'Osmium is the densest element; a brick of it weighs as much as two bricks of lead.' },
  Ir: { en:2.20, melt:2446 }, Pt: { en:2.28, melt:1768 },
  Au: { en:2.54, melt:1064, note:'All the gold ever mined would fit in a cube about twenty meters on a side.' },
  Hg: { en:2.00, melt:-39, note:'Mercury is the other room-temperature liquid; iron floats on it.' },
  Tl: { en:1.62, melt:304 }, Pb: { en:2.33, melt:328, note:'Lead is where uranium ends up: the last stop of its long decay chain.' },
  Bi: { en:2.02, melt:271 }, Po: { en:2.00, melt:254 }, At: { en:2.20, melt:302, est:true, note:'There is less than a gram of astatine in the whole Earth’s crust at any moment.' },
  Rn: { en:2.20, melt:-71 }, Fr: { en:0.70, melt:27, est:true }, Ra: { en:0.90, melt:700, note:'Radium glows faintly on its own, which is what made the old watch dials shine.' },
  Ac: { en:1.10, melt:1050 }, Th: { en:1.30, melt:1750 }, Pa: { en:1.50, melt:1572 },
  U:  { en:1.38, melt:1135, note:'Uranium was named for the planet found eight years before it.' },
  Np: { en:1.36, melt:644 }, Pu: { en:1.28, melt:640, note:'A lump of plutonium is warm to the touch from its own decay.' },
  Am: { en:1.13, melt:1176, note:'Americium is in most smoke detectors.' }, Cm: { en:1.28, melt:1345 },
  Bk: { en:1.30, melt:986 }, Cf: { en:1.30, melt:900 }, Es: { en:1.30, melt:860 },
  Fm: { en:1.30, melt:1527, est:true }, Md: { en:1.30, melt:827, est:true }, No: { en:1.30, melt:827, est:true }, Lr: { en:1.30, melt:1627, est:true },
  Rf: { en:null, melt:2100, est:true }, Db: { en:null, melt:null }, Sg: { en:null, melt:null }, Bh: { en:null, melt:null },
  Hs: { en:null, melt:null }, Mt: { en:null, melt:null }, Ds: { en:null, melt:null }, Rg: { en:null, melt:null },
  Cn: { en:null, melt:null }, Nh: { en:null, melt:null }, Fl: { en:null, melt:null }, Mc: { en:null, melt:null },
  Lv: { en:null, melt:null }, Ts: { en:null, melt:null },
  Og: { en:null, melt:null, note:'Oganesson: five or six atoms have ever been made, each gone in under a millisecond.' }
};
