// Snap! — the molecules panel data (step 3: all twenty-four lit, round B 2026-09-03).
// atoms: element symbols in landing order. pic: unit-square layout for the little picture
// (x,y in -1..1; r = ring size share) + bonds [i, j, order] ('i' = ionic).
window.SNAP_MOLECULES = [
  { key:'H2', name:'Hydrogen', formula:'H₂', atoms:['H','H'], lit:true,
    pic:{ a:[['H',-0.42,0],['H',0.42,0]], b:[[0,1,1]] },
    para:'A hydrogen atom has one electron, and its only shell has room for two. One is not stable; two is. When two hydrogen atoms come close, they share their two electrons between them. Each atom can now count both, so each has a full shell. That shared pair is a bond. Hydrogen is the simplest case of the rule every molecule here follows: atoms join up until their outer shells are full.',
    shape:'linear', bonds:'1 single', note:'Hydrogen gas is so light it leaks out of the top of the atmosphere and is gone.',
    land:'Hydrogen, landed apart. Each one wants one. <em>Bring them together.</em>' },
  { key:'H2O', name:'Water', formula:'H₂O', atoms:['O','H','H'], lit:true,
    pic:{ a:[['O',0,-0.18],['H',-0.62,0.5],['H',0.62,0.5]], b:[[0,1,1],[0,2,1]] },
    para:'Oxygen’s outer shell holds eight electrons but has only six, so it needs two more. Hydrogen’s shell holds two and has one, so each hydrogen needs one. Oxygen shares one electron with each hydrogen and gets one back from each. Count them: oxygen now has eight, and each hydrogen has two. Everyone is full, so the three atoms stay together. Oxygen also has two pairs of electrons it is not sharing. They take up room and push the hydrogens to one side, which is why water is bent instead of straight. The bend gives water a slightly positive end and a slightly negative end, and almost everything water does comes from that.',
    shape:'bent · 104.5°', bonds:'2 single', note:'The bend makes water a tiny magnet, which is why it sticks to itself and to almost everything.',
    land:'Water, landed apart. Oxygen wants two, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'O2', name:'Oxygen', formula:'O₂', atoms:['O','O'], lit:true,
    pic:{ a:[['O',-0.48,0],['O',0.48,0]], b:[[0,1,2]] },
    para:'Each oxygen atom has six electrons in an outer shell that holds eight, so each needs two. There is no third atom to help, so the two oxygens share two pairs of electrons with each other. That is a double bond. Count them: each atom has four unshared electrons of its own plus the four shared ones, which makes eight. Two shared pairs hold tighter than one, so a double bond takes more heat to break than a single bond.',
    shape:'linear', bonds:'1 double', note:'The oxygen you breathe is this pair; a single oxygen atom on its own does not last a second in air.',
    land:'Oxygen, landed apart. Each one wants two. <em>Bring them together, then drag one onto the other for the second pair.</em>' },
  { key:'CO2', name:'Carbon dioxide', formula:'CO₂', atoms:['C','O','O'], lit:true,
    pic:{ a:[['O',-0.78,0],['C',0,0],['O',0.78,0]], b:[[0,1,2],[1,2,2]] },
    para:'Carbon has four electrons in an outer shell that holds eight, so it needs four. Each oxygen has six and needs two. Carbon shares two pairs with one oxygen and two pairs with the other. That gives carbon eight (four of its own plus four shared) and gives each oxygen eight (six of its own plus two shared). Two double bonds, everyone full. The two bonds push away from each other and end up on opposite sides of the carbon, so the molecule is a straight line.',
    shape:'linear · 180°', bonds:'2 double', note:'Every breath out carries about forty thousand parts per million of it; the open air is about four hundred.',
    land:'Carbon dioxide, landed apart. Carbon wants four, each oxygen wants two. <em>Bring them together, then drag each oxygen onto the carbon for its second pair.</em>' },
  { key:'CH4', name:'Methane', formula:'CH₄', atoms:['C','H','H','H','H'], lit:true,
    pic:{ a:[['C',0,0],['H',-0.68,-0.6],['H',0.68,-0.6],['H',-0.68,0.6],['H',0.68,0.6]], b:[[0,1,1],[0,2,1],[0,3,1],[0,4,1]] },
    para:'Carbon has four electrons in an outer shell that holds eight. It needs four more, and it can share with up to four atoms at once. Hydrogen needs one. Four hydrogens each share their one electron with carbon, and carbon shares one back with each. Carbon ends up with eight and each hydrogen with two. The four bonds push away from each other as far as they can. On a flat screen that looks like a cross; in three dimensions it is a pyramid shape called a tetrahedron.',
    shape:'tetrahedral · 109.5°', bonds:'4 single', note:'Methane is the gas in a kitchen stove, and cows make about a bathtub of it a day.',
    land:'Methane, landed apart. Carbon wants four, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'NaCl', name:'Salt', formula:'NaCl', atoms:['Na','Cl'], lit:true,
    pic:{ a:[['Na',-0.5,0],['Cl',0.5,0]], b:[[0,1,'i']] },
    para:'Sodium has one electron in its outer shell, and the shell underneath is already full. Chlorine has seven in an outer shell that holds eight. Sodium does not share. It gives its one electron away, and chlorine takes it. Now both have full outer shells. But sodium has lost a negative charge, so it is now positive, and chlorine has gained one, so it is negative. Opposite charges attract, and that attraction is what holds salt together. This is an ionic bond, the other way atoms join. In real salt, every sodium is surrounded by six chlorines and every chlorine by six sodiums, in a cube-shaped crystal.',
    shape:'ionic pair', bonds:'1 ionic', note:'A grain of table salt is about a million billion of these pairs, stacked in a cube.',
    land:'Salt, landed apart. Sodium has one to give, chlorine wants one. <em>Bring them together.</em>' },
  { key:'N2', name:'Nitrogen', formula:'N₂', atoms:['N','N'], lit:true,
    pic:{ a:[['N', -0.48, 0], ['N', 0.48, 0]], b:[[0, 1, 3]] },
    para:'Each nitrogen has five electrons in an outer shell that holds eight, so each needs three. The two atoms share three pairs with each other. That is a triple bond. Count them: each atom has two unshared electrons plus six shared, which makes eight. Three shared pairs hold very tightly, which is why nitrogen gas is so hard to break apart, and why most of the air just sits there doing nothing.',
    shape:'linear', bonds:'1 triple', note:'Nitrogen is almost four fifths of the air. Getting the two atoms apart takes lightning, a bacterium, or a factory.',
    land:'Nitrogen, landed apart. Each one wants three. <em>Bring them together, then drag one onto the other twice more.</em>' },
  { key:'NH3', name:'Ammonia', formula:'NH₃', atoms:['N','H','H','H'], lit:true,
    pic:{ a:[['N', 0, -0.22], ['H', -0.72, 0.42], ['H', 0, 0.66], ['H', 0.72, 0.42]], b:[[0, 1, 1], [0, 2, 1], [0, 3, 1]] },
    para:'Nitrogen has five electrons in an outer shell that holds eight, so it needs three. Hydrogen needs one. Three hydrogens each share one electron with nitrogen, and nitrogen shares one back with each. Nitrogen ends up with eight: two of its own that stay unshared, plus six in the bonds. The unshared pair takes up room, so the three hydrogens are pushed to one side and the molecule is a low pyramid. That spare pair is also what lets ammonia grab onto acids.',
    shape:'pyramid · 107°', bonds:'3 single', note:'Ammonia is the sharp smell in glass cleaner, and most of the world’s fertilizer starts as ammonia.',
    land:'Ammonia, landed apart. Nitrogen wants three, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'HCl', name:'Hydrogen chloride', formula:'HCl', atoms:['H','Cl'], lit:true,
    pic:{ a:[['H', -0.55, 0], ['Cl', 0.42, 0]], b:[[0, 1, 1]] },
    para:'Chlorine has seven electrons in an outer shell that holds eight, so it needs one. Hydrogen has one electron and needs one more. They share one pair. Chlorine now counts eight and hydrogen counts two. Chlorine pulls harder on the shared pair than hydrogen does, so the chlorine end is slightly negative and the hydrogen end slightly positive. In water that pull is strong enough that the hydrogen lets go, and that is what makes hydrochloric acid an acid.',
    shape:'linear', bonds:'1 single', note:'Your stomach makes hydrochloric acid every day, strong enough to dissolve a nail.',
    land:'Hydrogen chloride, landed apart. Chlorine wants one, hydrogen wants one. <em>Bring them together.</em>' },
  { key:'HF', name:'Hydrogen fluoride', formula:'HF', atoms:['H','F'], lit:true,
    pic:{ a:[['H', -0.55, 0], ['F', 0.42, 0]], b:[[0, 1, 1]] },
    para:'Fluorine has seven electrons in an outer shell that holds eight, so it needs one. Hydrogen needs one. They share one pair, and both shells are full. Fluorine pulls on shared electrons harder than any other element, so this bond is lopsided: the fluorine end is strongly negative and the hydrogen end strongly positive. Neighboring molecules line up hydrogen to fluorine, which is why hydrogen fluoride boils at a much higher temperature than a molecule this small should.',
    shape:'linear', bonds:'1 single', note:'Hydrofluoric acid eats glass, so it is stored in plastic bottles.',
    land:'Hydrogen fluoride, landed apart. Fluorine wants one, hydrogen wants one. <em>Bring them together.</em>' },
  { key:'Cl2', name:'Chlorine', formula:'Cl₂', atoms:['Cl','Cl'], lit:true,
    pic:{ a:[['Cl', -0.5, 0], ['Cl', 0.5, 0]], b:[[0, 1, 1]] },
    para:'Each chlorine has seven electrons in an outer shell that holds eight, so each needs one. The two atoms share one pair. Count them: each has six unshared electrons plus the two shared ones, which makes eight. A single bond between two large atoms is not very strong, so chlorine gas comes apart easily and reacts with almost anything it meets.',
    shape:'linear', bonds:'1 single', note:'Chlorine gas is yellow-green, and its name is the Greek word for that color.',
    land:'Chlorine, landed apart. Each one wants one. <em>Bring them together.</em>' },
  { key:'F2', name:'Fluorine', formula:'F₂', atoms:['F','F'], lit:true,
    pic:{ a:[['F', -0.5, 0], ['F', 0.5, 0]], b:[[0, 1, 1]] },
    para:'Each fluorine has seven electrons in an outer shell that holds eight, so each needs one. They share one pair, and both count eight. The bond is weak, because the unshared electrons on two small atoms are crowded close together and push each other away. A bond that breaks easily, plus the strongest pull on electrons of any element, makes fluorine the most reactive gas there is.',
    shape:'linear', bonds:'1 single', note:'Fluorine will burn water, glass, and brick.',
    land:'Fluorine, landed apart. Each one wants one. <em>Bring them together.</em>' },
  { key:'H2O2', name:'Hydrogen peroxide', formula:'H₂O₂', atoms:['H','O','O','H'], lit:true,
    pic:{ a:[['H', -0.92, 0.42], ['O', -0.36, -0.14], ['O', 0.36, 0.14], ['H', 0.92, -0.42]], b:[[0, 1, 1], [1, 2, 1], [2, 3, 1]] },
    para:'Each oxygen has six electrons in an outer shell that holds eight, so each needs two. Here the two oxygens share one pair with each other, and each shares one pair with a hydrogen. Count an oxygen: four unshared, plus two shared with the other oxygen, plus two shared with hydrogen, makes eight. Everyone is full. But an oxygen-to-oxygen single bond is weak, and the molecule falls apart easily into water and oxygen gas. That is why peroxide fizzes on a cut, and why it is sold in dark bottles.',
    shape:'twisted chain', bonds:'3 single', note:'Hydrogen peroxide bleaches hair by breaking the pigment apart, one molecule at a time.',
    land:'Hydrogen peroxide, landed apart. Each oxygen wants two, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'C2H4', name:'Ethene', formula:'C₂H₄', atoms:['C','C','H','H','H','H'], lit:true,
    pic:{ a:[['C', -0.38, 0], ['C', 0.38, 0], ['H', -0.88, -0.6], ['H', -0.88, 0.6], ['H', 0.88, -0.6], ['H', 0.88, 0.6]], b:[[0, 1, 2], [0, 2, 1], [0, 3, 1], [1, 4, 1], [1, 5, 1]] },
    para:'Each carbon has four electrons in an outer shell that holds eight, so each needs four. The two carbons share two pairs with each other, a double bond, and each carbon shares one pair with each of two hydrogens. Count a carbon: four shared with the other carbon, plus two shared with each hydrogen, makes eight. The double bond holds the whole molecule flat. It is also the weak spot: one of the two pairs can open up and grab another molecule, which is how ethene links into long chains.',
    shape:'flat · 120°', bonds:'1 double, 4 single', note:'Ethene is the gas that ripens fruit, and the raw material for polyethylene, the most common plastic.',
    land:'Ethene, landed apart. Each carbon wants four, each hydrogen wants one. <em>Two hydrogens on each carbon, carbon to carbon, then one carbon onto the other.</em>' },
  { key:'C2H6', name:'Ethane', formula:'C₂H₆', atoms:['C','C','H','H','H','H','H','H'], lit:true,
    pic:{ a:[['C', -0.4, 0], ['C', 0.4, 0], ['H', -0.92, -0.5], ['H', -0.92, 0.5], ['H', -0.4, -0.8], ['H', 0.92, -0.5], ['H', 0.92, 0.5], ['H', 0.4, 0.8]], b:[[0, 1, 1], [0, 2, 1], [0, 3, 1], [0, 4, 1], [1, 5, 1], [1, 6, 1], [1, 7, 1]] },
    para:'Each carbon has four electrons in an outer shell that holds eight. The two carbons share one pair with each other, and each carbon shares one pair with each of three hydrogens. Count a carbon: two shared with the other carbon plus six shared with hydrogens makes eight. Every hydrogen has two. Nothing is left over and nothing is doubled, so ethane is a quiet molecule. The two halves can even spin freely around the single bond between them.',
    shape:'two tetrahedra', bonds:'7 single', note:'Ethane is the second-largest part of natural gas, after methane.',
    land:'Ethane, landed apart. Each carbon wants four, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'C2H2', name:'Acetylene', formula:'C₂H₂', atoms:['C','C','H','H'], lit:true,
    pic:{ a:[['C', -0.3, 0], ['C', 0.3, 0], ['H', -0.92, 0], ['H', 0.92, 0]], b:[[0, 1, 3], [0, 2, 1], [1, 3, 1]] },
    para:'Each carbon has four electrons in an outer shell that holds eight. The two carbons share three pairs with each other, a triple bond, and each carbon shares one pair with a hydrogen. Count a carbon: six shared with the other carbon plus two shared with hydrogen makes eight. A triple bond pulls everything into a straight line. It also stores a lot of energy, which comes out as heat when acetylene burns.',
    shape:'linear · 180°', bonds:'1 triple, 2 single', note:'An acetylene torch burns hot enough to cut steel.',
    land:'Acetylene, landed apart. Each carbon wants four, each hydrogen wants one. <em>One hydrogen each, carbon to carbon, then one carbon onto the other twice more.</em>' },
  { key:'CH3OH', name:'Methanol', formula:'CH₃OH', atoms:['C','O','H','H','H','H'], lit:true,
    pic:{ a:[['C', -0.36, 0.04], ['O', 0.4, -0.1], ['H', -0.9, -0.48], ['H', -0.9, 0.56], ['H', -0.36, -0.74], ['H', 0.9, 0.5]], b:[[0, 1, 1], [0, 2, 1], [0, 3, 1], [0, 4, 1], [1, 5, 1]] },
    para:'Carbon has four electrons in an outer shell that holds eight, oxygen has six, and each hydrogen has one in a shell that holds two. Carbon shares one pair with oxygen and one pair with each of three hydrogens: eight. Oxygen shares one pair with carbon and one with the last hydrogen, and keeps two pairs unshared: eight. Methanol is methane with one hydrogen swapped for an oxygen-and-hydrogen group. That group is slightly charged at one end, so methanol mixes with water.',
    shape:'bent at the oxygen', bonds:'5 single', note:'Methanol is wood alcohol. A few tablespoons can blind a person, and a little is in most windshield washer fluid.',
    land:'Methanol, landed apart. Carbon wants four, oxygen wants two, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'CH2O', name:'Formaldehyde', formula:'CH₂O', atoms:['C','O','H','H'], lit:true,
    pic:{ a:[['C', 0, 0.12], ['O', 0, -0.6], ['H', -0.68, 0.6], ['H', 0.68, 0.6]], b:[[0, 1, 2], [0, 2, 1], [0, 3, 1]] },
    para:'Carbon has four electrons in an outer shell that holds eight, so it needs four. Oxygen has six and needs two. Carbon shares two pairs with oxygen, a double bond, and one pair with each of two hydrogens. Count carbon: four shared with oxygen plus two with each hydrogen makes eight. Oxygen has four unshared plus four shared: eight. The carbon-oxygen double bond is the reactive part, and it is why formaldehyde attaches so readily to the proteins in living tissue.',
    shape:'flat · 120°', bonds:'1 double, 2 single', note:'Formaldehyde is what preserves the specimens in jars in a biology lab.',
    land:'Formaldehyde, landed apart. Carbon wants four, oxygen wants two, each hydrogen wants one. <em>Both hydrogens on the carbon, oxygen to carbon, then the oxygen onto the carbon again.</em>' },
  { key:'H2S', name:'Hydrogen sulfide', formula:'H₂S', atoms:['S','H','H'], lit:true,
    pic:{ a:[['S', 0, -0.18], ['H', -0.62, 0.5], ['H', 0.62, 0.5]], b:[[0, 1, 1], [0, 2, 1]] },
    para:'Sulfur sits right under oxygen on the table, and like oxygen it has six electrons in an outer shell that holds eight. So it needs two, and it takes one share from each of two hydrogens, exactly like water. Count sulfur: four unshared plus four shared makes eight. The shape is bent like water, but sulfur is a bigger atom and holds its electrons more loosely, so the molecule is less sticky. It is a gas at room temperature, where water is a liquid.',
    shape:'bent · 92°', bonds:'2 single', note:'Hydrogen sulfide is the rotten-egg smell. In large amounts it is as deadly as cyanide.',
    land:'Hydrogen sulfide, landed apart. Sulfur wants two, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'MgCl2', name:'Magnesium chloride', formula:'MgCl₂', atoms:['Mg','Cl','Cl'], lit:true,
    pic:{ a:[['Cl', -0.74, 0], ['Mg', 0, 0], ['Cl', 0.74, 0]], b:[[1, 0, 'i'], [1, 2, 'i']] },
    para:'Magnesium has two electrons in its outer shell, and the shell underneath is full. Each chlorine has seven in an outer shell that holds eight. Magnesium gives one electron to each chlorine. Now all three have full outer shells. Magnesium has lost two negative charges, so it is Mg²⁺; each chlorine has gained one, so it is Cl⁻. Two negatives balance one double positive, which is why the formula has two chlorines. The charges hold the whole crystal together.',
    shape:'ionic · 1 to 2', bonds:'2 ionic', note:'Magnesium chloride is most of what is left when seawater evaporates after the table salt comes out.',
    land:'Magnesium chloride, landed apart. Magnesium has two to give, each chlorine wants one. <em>Bring them together.</em>' },
  { key:'LiF', name:'Lithium fluoride', formula:'LiF', atoms:['Li','F'], lit:true,
    pic:{ a:[['Li', -0.5, 0], ['F', 0.5, 0]], b:[[0, 1, 'i']] },
    para:'Lithium has one electron in its outer shell, and the shell underneath holds two and is full. Fluorine has seven in an outer shell that holds eight. Lithium gives its one electron to fluorine. Both are now full. Lithium is positive, fluorine is negative, and the charges hold them together. Both ions are small, so they sit very close, and this is one of the strongest ionic bonds there is.',
    shape:'ionic pair', bonds:'1 ionic', note:'Lithium fluoride is so hard to pull apart that it melts at over 800 °C.',
    land:'Lithium fluoride, landed apart. Lithium has one to give, fluorine wants one. <em>Bring them together.</em>' },
  { key:'C3H8', name:'Propane', formula:'C₃H₈', atoms:['C','C','C','H','H','H','H','H','H','H','H'], lit:true,
    pic:{ a:[['C', -0.62, 0.12], ['C', 0, -0.26], ['C', 0.62, 0.12], ['H', -0.98, -0.42], ['H', -0.98, 0.6], ['H', -0.5, 0.72], ['H', -0.22, -0.84], ['H', 0.22, -0.84], ['H', 0.98, -0.42], ['H', 0.98, 0.6], ['H', 0.5, 0.72]], b:[[0, 1, 1], [1, 2, 1], [0, 3, 1], [0, 4, 1], [0, 5, 1], [1, 6, 1], [1, 7, 1], [2, 8, 1], [2, 9, 1], [2, 10, 1]] },
    para:'Three carbons in a row, each with four electrons in an outer shell that holds eight. Each carbon shares one pair with its neighbor carbon and fills the rest of its eight with hydrogens: three on each end carbon, two on the middle one. Count the middle carbon: two shared with each neighbor plus two with each hydrogen makes eight. Every hydrogen has two. Chains like this are the pattern for all the fuels. The longer the chain, the harder it is to boil. Propane is three carbons long, so it is a gas that turns to liquid under a little pressure.',
    shape:'zigzag chain', bonds:'10 single', note:'Propane is the fuel in a grill tank. It is stored as a liquid and comes out as a gas.',
    land:'Propane, landed apart. Each carbon wants four, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'SiH4', name:'Silane', formula:'SiH₄', atoms:['Si','H','H','H','H'], lit:true,
    pic:{ a:[['Si', 0, 0], ['H', -0.68, -0.6], ['H', 0.68, -0.6], ['H', -0.68, 0.6], ['H', 0.68, 0.6]], b:[[0, 1, 1], [0, 2, 1], [0, 3, 1], [0, 4, 1]] },
    para:'Silicon sits right under carbon on the table, and like carbon it has four electrons in an outer shell that holds eight. Four hydrogens each share one electron with silicon, and silicon shares one back with each. Silicon counts eight, each hydrogen counts two, and the shape is the same tetrahedron as methane. But silicon is a bigger atom and holds hydrogen more loosely, so silane is far less stable than methane. It catches fire on contact with air.',
    shape:'tetrahedral · 109.5°', bonds:'4 single', note:'Silane lays down the thin layers of silicon in computer chips and solar cells.',
    land:'Silane, landed apart. Silicon wants four, each hydrogen wants one. <em>Bring them together.</em>' },
  { key:'C6H6', name:'Benzene', formula:'C₆H₆', atoms:['C','C','C','C','C','C','H','H','H','H','H','H'], lit:true,
    pic:{ a:[['C', 0.0, 0.5], ['C', -0.43, 0.25], ['C', -0.43, -0.25], ['C', -0.0, -0.5], ['C', 0.43, -0.25], ['C', 0.43, 0.25], ['H', 0.0, 0.92], ['H', -0.8, 0.46], ['H', -0.8, -0.46], ['H', -0.0, -0.92], ['H', 0.8, -0.46], ['H', 0.8, 0.46]], b:[[0, 1, 2], [1, 2, 1], [2, 3, 2], [3, 4, 1], [4, 5, 2], [5, 0, 1], [0, 6, 1], [1, 7, 1], [2, 8, 1], [3, 9, 1], [4, 10, 1], [5, 11, 1]] },
    para:'Six carbons in a ring, each with four electrons in an outer shell that holds eight. In the drawing, each carbon shares one pair with one neighbor, two pairs with the other, and one pair with a hydrogen. Count a carbon: two plus four plus two makes eight. The truth is stranger. The six extra electrons in the double bonds do not stay put; they spread evenly around the whole ring, so every carbon-carbon bond is the same length, halfway between single and double. That shared ring of electrons makes benzene unusually stable, and it is the core of thousands of other molecules.',
    shape:'flat hexagon', bonds:'6 ring + 6 single', note:'Benzene was in gasoline for decades before anyone knew it causes leukemia.',
    land:'Benzene, landed apart. Each carbon wants four, each hydrogen wants one. <em>One hydrogen each, chain the carbons, close the ring, then every other carbon bond up to a double.</em>' },
];

// the little picture: rings in the appetite tints, a lens on each shared pair, a warm/cool pair for ionic
window.SNAP_MINI = function(canvas, mol, tintOf){
  const pic=mol.pic; if(!pic) return;
  const dpr=Math.min(3, window.devicePixelRatio||1); const W=canvas.clientWidth||64, H=canvas.clientHeight||44;
  canvas.width=Math.round(W*dpr); canvas.height=Math.round(H*dpr); const ctx=canvas.getContext('2d'); ctx.scale(dpr,dpr);
  const cx=W/2, cy=H/2, ux=W*0.46, uy=H*0.44, u=Math.min(ux,uy); const n=pic.a.length; const rs = n<=5 ? 1 : Math.sqrt(5/n); // unit → px; big molecules get smaller rings
  const P=pic.a.map(([s,x,y])=>({ s, x:cx+x*ux, y:cy+y*uy, r:(s==='H'?0.34:0.5)*u*rs, c:tintOf(s) }));
  const hexA=(h,a)=>{ const n=parseInt(h.slice(1),16); return 'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+a+')'; };
  for(const [i,j,o] of pic.b){ const A=P[i], B=P[j]; const mx=(A.x+B.x)/2, my=(A.y+B.y)/2, ang=Math.atan2(B.y-A.y,B.x-A.x);
    if(o==='i'){ ctx.save(); ctx.setLineDash([2,3]); const g=ctx.createLinearGradient(A.x,A.y,B.x,B.y); g.addColorStop(0,'rgba(240,160,96,0.7)'); g.addColorStop(1,'rgba(95,184,240,0.7)'); ctx.strokeStyle=g; ctx.lineWidth=1; ctx.beginPath(); ctx.moveTo(A.x,A.y); ctx.lineTo(B.x,B.y); ctx.stroke(); ctx.restore(); continue; }
    ctx.save(); ctx.translate(mx,my); ctx.rotate(ang); const w=3+2*o, h=u*0.42; const g=ctx.createRadialGradient(0,0,0,0,0,h); g.addColorStop(0,'rgba(255,255,255,0.95)'); g.addColorStop(0.35,'rgba(219,238,255,0.55)'); g.addColorStop(1,'rgba(160,205,255,0)');
    ctx.fillStyle=g; ctx.beginPath(); ctx.ellipse(0,0,w,h,0,0,Math.PI*2); ctx.fill(); ctx.restore(); }
  for(const p of P){ const g=ctx.createRadialGradient(p.x,p.y,p.r*0.2,p.x,p.y,p.r*1.15); g.addColorStop(0,hexA(p.c,0.28)); g.addColorStop(1,hexA(p.c,0)); ctx.fillStyle=g; ctx.beginPath(); ctx.arc(p.x,p.y,p.r*1.15,0,Math.PI*2); ctx.fill();
    ctx.strokeStyle=hexA(p.c,0.95); ctx.lineWidth=1.1; ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2); ctx.stroke();
    ctx.fillStyle=hexA(p.c,0.9); ctx.beginPath(); ctx.arc(p.x,p.y,p.r*0.22,0,Math.PI*2); ctx.fill(); }
  for(const [i,j,o] of pic.b){ if(o==='i'){ const A=P[i], B=P[j]; ctx.fillStyle='rgba(240,160,96,0.9)'; ctx.beginPath(); ctx.arc(A.x+A.r*0.7,A.y-A.r*0.7,1.6,0,Math.PI*2); ctx.fill(); ctx.fillStyle='rgba(95,184,240,0.9)'; ctx.beginPath(); ctx.arc(B.x+B.r*0.7,B.y-B.r*0.7,1.6,0,Math.PI*2); ctx.fill(); continue; }
    const A=P[i], B=P[j]; const mx=(A.x+B.x)/2, my=(A.y+B.y)/2, ang=Math.atan2(B.y-A.y,B.x-A.x); const px=-Math.sin(ang), py=Math.cos(ang);
    for(let k=0;k<o;k++){ const off=(k-(o-1)/2)*3.2; ctx.fillStyle='rgba(30,40,60,0.9)'; ctx.beginPath(); ctx.arc(mx+px*off+Math.cos(ang)*1.4,my+py*off+Math.sin(ang)*1.4,0.9,0,Math.PI*2); ctx.arc(mx+px*off-Math.cos(ang)*1.4,my+py*off-Math.sin(ang)*1.4,0.9,0,Math.PI*2); ctx.fill(); } }
};
